crops:
  BEETROOTS:
    -  BEETROOT
    -  BEETROOT_SEEDS
  CARROTS:
    -  CARROT
  POTATOES:
    -  POTATO
  WHEAT:
    -  WHEAT
    -  WHEAT_SEEDS
  MELON:
    -  MELON
  PUMPKIN:
    -  PUMPKIN
  PUMPKIN_STEM:
    -  PUMPKIN_SEEDS
  ATTACHED_PUMPKIN_STEM:
    -  PUMPKIN_SEEDS
  ATTACHED_MELON_STEM:
    -  MELON_SEEDS
  MELON_STEM:
    -  MELON_SEEDS 
tools:
  -  DIAMOND_HOE
  -  GOLDEN_HOE
  -  IRON_HOE
  -  STONE_HOE
  -  WOODEN_HOE
  